name: Deploy to prod
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Save Image (Compressed)
        run: |
          docker build -t kalovrat-admin .
          # Сжимаем образ "на лету" для уменьшения размера файла
          docker save kalovrat-admin | gzip > kalovrat-admin.tar.gz

      - name: Copy image to VDS
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "kalovrat-admin.tar.gz"
          target: "/tmp"

      - name: Load and Restart with Bun
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            # Распаковываем и загружаем образ
            zcat /tmp/kalovrat-admin.tar.gz | docker load
            
            # Удаляем старый контейнер
            docker stop kalovrat-admin || true
            docker rm kalovrat-admin || true
            
            # Запускаем новый
            docker run -d \
              -p 3100:3000 \
              --name kalovrat-admin \
              --restart always \
              -e DATABASE_URL=${{ secrets.DB_URL }} \
              -e ADMIN_LOGIN=${{ secrets.ADMIN_LOGIN }} \
              -e ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }} \
              kalovrat-admin
            
            # Очистка
            rm /tmp/kalovrat-admin.tar.gz
            docker image prune -f
